# Generated by Django 6.0.1 on 2026-02-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('etf', 'ETF')], default='stock', max_length=10),
            preserve_default=False,
        ),
    ]
