# Generated by Django 6.0.1 on 2026-02-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(help_text='eg. PETR4, VALE3)', max_length=10),
        ),
    ]
