# Generated by Django 5.2 on 2026-02-25 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_alter_asset_ticker"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price", models.DecimalField(decimal_places=10, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
    ]
