# Generated by Django 5.2 on 2026-03-03 17:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_assetprice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="asset",
            old_name="ticker",
            new_name="symbol",
        ),
        migrations.AlterUniqueTogether(
            name="asset",
            unique_together={("user", "symbol")},
        ),
    ]
