# Generated by Django 6.0.1 on 2026-02-04 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_alter_asset_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('check_interval_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunnels', to='assets.asset')),
            ],
            options={
                'unique_together': {('asset', 'lower_limit', 'upper_limit')},
            },
        ),
    ]
