# Generated by Django 5.2 on 2026-02-26 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("tunnels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicTaskAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "periodic_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
                (
                    "tunnel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_task_associations",
                        to="tunnels.pricetunnel",
                    ),
                ),
            ],
            options={
                "unique_together": {("periodic_task", "tunnel")},
            },
        ),
    ]
