# Generated by Django 5.2 on 2026-03-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tunnels", "0002_periodictaskassociation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricetunnel",
            name="check_interval_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
